# Generated by Django 5.1.1 on 2024-09-03 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desenvolvedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobre', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tipo_user', models.CharField(choices=[('DEV', 'Desenvolvedor'), ('DIST', 'Distribuidora'), ('CLI', 'Cliente')], default='ClI', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('desenvolvedores_associados', models.ManyToManyField(blank=True, related_name='desenvolvedores_associados', to='Jogos.desenvolvedor')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('data_lançamento', models.DateField()),
                ('sobre_o_jogo', models.TextField()),
                ('preço', models.FloatField(default=0)),
                ('desenvolvedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jogos.desenvolvedor')),
                ('distribuidora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Jogos.distribuidora')),
            ],
        ),
        migrations.AddField(
            model_name='distribuidora',
            name='jogo_distribuidos',
            field=models.ManyToManyField(blank=True, related_name='jogo_distribuidora', to='Jogos.jogo'),
        ),
        migrations.AddField(
            model_name='desenvolvedor',
            name='jogos_lançados',
            field=models.ManyToManyField(blank=True, related_name='jogos_lançados', to='Jogos.jogo'),
        ),
    ]
