# Generated by Django 5.1.1 on 2024-09-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jogos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipo_user',
        ),
    ]
